# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7c51f2ef51a2d2da094ca6fb59059e186e2d1f83be958ad6aa11f91b3f305ad7c4efe1b685e8da1ea00f543db08c7bc863fc5cafdb084d5e2ca91d16887af90

test:
  secret_key_base: 0288ee57812de5f76832a7a3814196abcebd3af3f9ce4b2994a3c79e96036377ce2039a9a7c6228553ef6aa327989fe7c66d69de04e5137c5c5c1d1543bd94b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
